# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3cd740928129538f913c5653c5cad911eb715acb81227ba871e98c7786ae7db0d3dea30b7fc04333b14b83d28af215da8156e7cd9dfdf6b0c95f69fc0d9d4da1

test:
  secret_key_base: 4e7f8f4c22fe296b8c95f5b3b5aff617f4b7eca72b7f162890f4d21eb4353dc344694a82700b371e127e615fe6d5af6eca66a3ef819c0912cb0a6a054958b0bf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
